name: Stock Data Fetcher

on:
  schedule:
    # 每个工作日的 UTC 时间 02:00 执行（北京时间 10:00）
    - cron: '0 2 * * 1-5'
  
  # 允许手动触发
  workflow_dispatch:

jobs:
  fetch-stock-data:
    runs-on: ubuntu-latest
    environment: stock_usage

    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Checkout private tools
      uses: actions/checkout@v4
      with:
        repository: zning1994/equity_date_fetching
        branch: main
        token: ${{ secrets.PRIVATE_TOEKEN }}
        path: scripts
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        cd scripts;
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run stock data fetcher
      run: |
        cd scripts;
        python main.py
      env:
        TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
        OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
        OSS_BUCKET_NAME: ${{ secrets.OSS_BUCKET_NAME }}
        OSS_ENDPOINT: ${{ secrets.OSS_ENDPOINT }}
    
    - name: Upload logs as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: stock-fetcher-logs
        path: stock_fetcher.log
        retention-days: 30 

    - name: Commit files
      run: |
        git config --local user.email "zhn038@gmail.com"
        git config --local user.name "ZNing"
        git add .
        git commit -m "$(date "+%Y-%m-%d %H:%M:%S")"
 
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
